version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      APP_PORT: 3001
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: homen